-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schemas/table.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE urlshortcodes (
  usc_id SERIAL NOT NULL,
  usc_url_hash CHAR(32) NOT NULL,
  usc_url TEXT NOT NULL,
  usc_deleted SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(usc_id)
);

CREATE UNIQUE INDEX urlshortcodes_url_hash ON urlshortcodes (usc_url_hash);
